# Prefix
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# Mouse
set -g mouse on

# Índice começa em 1
set -g base-index 1
set -g pane-base-index 1

# Ghostty
set -g default-terminal "ghostty"
set-option -sa terminal-features ',ghostty:RGB'

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Config recarregada!"

# Splits intuitivos
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Navegação estilo vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
