# CONFIGURAÇÃO GERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# PLANO DE FUNDO
background {
    monitor =
    path = /home/kadu/.config/backgrounds/astronaut.png
    color = rgba(30, 30, 46, 1.0)
    blur_passes = 3
    blur_size = 2
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# CAMPO DE SENHA
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(116, 199, 236, 0.5) # Azul transparente
    inner_color = rgba(30, 30, 46, 0.8)    # Fundo escuro
    font_color = rgb(205, 214, 244)        # Texto claro
    fade_on_empty = false
    
    # Placeholder apenas com cadeado
    placeholder_text = <span foreground="##cdd6f4"> $USER</span>
    font_family = JetBrains Mono Nerd Font
    
    hide_input = false
    rounding = -1
    
    check_color = rgb(249, 226, 175)
    fail_color = rgb(243, 139, 168)
    fail_text = <i>Falha na autenticação</i>
    
    # Posição (Abaixo da data)
    position = 0, -270
    halign = center
    valign = center
}

# --- RELÓGIO PARTE 1: HORA (EM CIMA) ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = rgba(205, 214, 244, 0.8) 
    font_size = 150
    font_family = Bowlby One SC
    shadow_boost = 1.2
    
    # Posição bem alta
    position = 0, -180
    halign = center
    valign = top
}

# --- RELÓGIO PARTE 2: MINUTOS (EMBAIXO) ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgba(205, 214, 244, 0.8)
    font_size = 150
    font_family = Bowlby One SC
    shadow_boost = 1.2
    
    # Posição logo abaixo da hora (Ajuste o Y se ficarem sobrepostos)
    position = 0, -360
    align = center
    valign = top
}

# DATA
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d de %B")"
    color = rgba(205, 214, 244, 0.8)
    font_size = 24
    font_family = La Belle Aurore
    shadow_boost = 1.2
    
    # Abaixo dos minutos
    position = 0, -90 
    halign = center
    valign = center
}
